# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

archetypeDir                         = "archetypes"
assetDir                             = "assets"
baseURL                              = "https://delimaresidences.com/"
buildDrafts                          = false
buildExpired                         = false
buildFuture                          = false
canonifyURLs                         = false
capitalizeListTitles                 = true
cleanDestinationDir                  = false
contentDir                           = "content"
dataDir                              = "data"
defaultContentLanguage               = "id"
defaultContentLanguageInSubdir       = false
disableAliases                       = false
disableHugoGeneratorInject           = false
disableLiveReload                    = false
disablePathToLower                   = false
enableEmoji                          = false
enableGitInfo                        = false
enableMissingTranslationPlaceholders = false
enableRobotsTXT                      = true
hasCJKLanguage                       = false
newContentEditor                     = ""
noChmod                              = false
noTimes                              = false
paginate                             = 10
paginatePath                         = "page"
pluralizeListTitles                  = true
publishDir                           = "public"
refLinksErrorLevel                   = "ERROR"
refLinksNotFoundURL                  = ""
relativeURLs                         = false
removePathAccents                    = false
summaryLength                        = 70
theme                                = "blowfish"
themesDir                            = "themes"
timeZone                             = "Asia/Jakarta"
timeout                              = "30s"
titleCaseStyle                       = "ap"
uglyURLs                             = false
watch                                = false

[taxonomies]
author   = "authors"
category = "categories"
series   = "series"
tag      = "tags"

[sitemap]
changefreq = 'daily'
filename   = 'sitemap.xml'
priority   = 0.5

[outputs]
home = [ "HTML", "JSON", "RSS" ]

[build]
[caches]
[frontmatter]
[imaging]
[markup]
[mediaTypes]
[minify]
[outputFormats]
[permalinks]
[related]
[security]
[segments]
