languageCode = "id-ID"
languageName = "Indonesian"
title        = "Rudy 1990 Samarinda"
weight       = 1

[params]
copyright     = "Kontribusi di **[GitHub](https://github.com/andrewsulisthio/rudy1990.com)**"
dateFormat    = "2 January 2006"
description   = "Rudy 1990 Samarinda"
displayName   = "ID"
isoCode       = "id"
logo          = "img/small_logo.png"
rtl           = false
secondaryLogo = ""

[author]
bio      = "Rudy 1990 Samarinda"
headline = "Rudy 1990 Samarinda"
image    = "img/medium_logo.png"
links    = [  ]
name     = "Rudy 1990 Samarinda"
