backend:
    name: github
    repo: andrewsulisthio/delimaresidences.com
    branch: content-update
    base_url: https://delimaresidences.com

media_folder: ""
public_folder: ""

collections:
    - name: "home"
      label: "Homepage"
      files:
          - label: "Homepage"
            name: "homepage"
            file: "content/_index.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Publish Date", name: "date", widget: "datetime" }
                - {
                      label: "featured.jpg or featured.png",
                      name: "featuredImage",
                      widget: "image",
                      default: "featured.jpg",
                  }
                - { label: "Body", name: "body", widget: "markdown" }
    - name: "pengumuman"
      label: "Pengumuman"
      folder: "content/pengumuman"
      path: "{{slug}}/index"
      create: true
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "featured.jpg or featured.png",
                name: "featuredImage",
                widget: "image",
                default: "featured.jpg",
            }
          - { label: "Body", name: "body", widget: "markdown" }
    - name: "merdeka-in-mozaic"
      label: "Merdeka in Mozaic"
      folder: "content/merdeka-in-mozaic"
      path: "{{slug}}/index"
      create: true
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - {
                label: "featured.jpg or featured.png",
                name: "featuredImage",
                widget: "image",
                default: "featured.jpg",
            }
          - { label: "Body", name: "body", widget: "markdown" }